### PR TITLE
Fix @BeginCode, add test

### LINKED ISSUE #227: Inserting code blocks is broken
https://github.com/gap-packages/AutoDoc/pull/218 breaks inserting code blocks.

Steps to reproduce:
1. Replace `Chunk` by `Code` in `tst/worksheets/general.sheet/worksheet.g`
2. Run tests

Expected result: `Hello, world` appears in `tst/worksheets/general.actual/_Chunks.xml`.

Actual result: `Hello, world` does not appear in `tst/worksheets/general.actual/_Chunks.xml`.

Real life example: https://github.com/homalg-project/CAP_project/blob/master/CAP/doc/Limits.autodoc#L40

### PR DESCRIPTION
**Pull request by fingolfin**
Fixes #227

Ping @zickgraf -- can you confirm?

### CODE REVIEW

**Comment by zickgraf** [comment]
The code is now inserted but the indentation is lost :-(

Example:
```
@BeginCode example_limit_record
rec(
  object_specification := [ "fixedobject", "varobject" ],
  morphism_specification := [ [ 2, "varmorphism", 1 ] ],
  limit_object_name := "FiberProduct",
  colimit_object_name := "Pushout",
)
@EndCode

@InsertCode example_limit_record
```
is rendered as
```
rec(
object_specification := [ "fixedobject", "varobject" ],
morphism_specification := [ [ 2, "varmorphism", 1 ] ],
limit_object_name := "FiberProduct",
colimit_object_name := "Pushout",
)
```

**Comment by fingolfin** [comment]
Weird.

Anyway, it is a bit difficult to debug all this, as the semantics for `@BeginCode`, `@BeginExample`, etc. are almost completely undocumented, in particular how they interact with comments / AutoDoc comments / anything else. It is now a matter of reverse engineering what a given implementation happened to do at some point, including all weird and odd things about it; and any attempt to make something less weird of course risks breaking somebodies usecase *sigh*

**Comment by fingolfin** [comment]
@zickgraf I applied a hack which should fix your issue, but has new problems. I need to think some more about this

**Comment by zickgraf** [comment]
I can confirm that the WIP commit fixes my issue.

**Comment by fingolfin** [comment]
New idea (as just discussed): We imitate GAPDoc: After finding a `@BeginCode`, we record whatever came before it on the line as a PREFIX. Then in all subsequent lines, we take the maximal common prefix of that line, and the recorded PREFIX, and remove that from the line we just read, and store/process the rest of the line; we repeat this until we encounter the matching `@EndCode`. 

This should take care of weird indentation quirks. Of course this should be documented, and also applied to other similar constructs.

**Comment by fingolfin** [comment]
Let's merge this for now: it's not perfect, but resolves the immediate issue at hand.

**Pull request merged**
