### PR TITLE
Tests: rebased and modified PR #180

### PR DESCRIPTION
**Pull request by fingolfin**

### CODE REVIEW

**Comment by alex-konovalov** [comment]
@fingolfin How do the tests depend on the availability of LaTeX? Could you have a test to specify in PackageInfo.g so it can be picked up by other automated testing?

**Comment by fingolfin** [comment]
These tests run GAPDoc, so they require LaTeX

**Comment by alex-konovalov** [comment]
That will not be an obstacle to run them on our Jenkins nodes. If you don't have a separation for latex-free tests (yet?), just add all and I will see what happens.

**Comment by sebasguts** [comment]
I am happy with this, thank you :)

**Pull request merged**
