### PR TITLE
Provide `@NotLatex` in addition to `@LatexOnly`

### LINKED ISSUE #186: Provide `@NotLatex` in addition to `@LatexOnly`

### PR DESCRIPTION
**Pull request by zickgraf**
Fixes #186

Note: I have no deep understanding of the parser code. I have just copied the `LatexOnly` parts and in my tests everything works.

### CODE REVIEW

**Comment by fingolfin** [comment]
Coverage drops because of this. It would be nice if there was a test for this, e.g. by editing `tst/worksheets/general.sheet/worksheet.g` suitably, then updating the content of `tst/worksheets/general.expected/`  accordingly (we probably should provide a script to take care of the latter... I'll file an issue)

**Comment by fingolfin** [comment]
Anyway, I am also fine with merging this as-is, and then we add tests later. We don't test many other things right now either, so who am I to complain :-/

**Comment by zickgraf** [comment]
I have added tests for both `LatexOnly` and `NotLatex` and hope that this will increase the coverage.

**Comment by sebasguts** [comment]
Very nice!

**Pull request merged**
